### PR TITLE
created Calendar feature file, StepDefinition, CalendarPage

### PR DESCRIPTION
**Pull request by ibobechko**

### CODE REVIEW

**Review by ValeriySyutkin — APPROVED** [review]
impressive. So you are done with your project too :)

**Comment by ibobechko** [comment]
Almost :)) I only need to automate one more step but I feel like I’m done
for today :)

**Comment by ValeriySyutkin** [comment]
i  have tried to run your test and @newEvent scenario doesn't go through . Rest scenarios are good. Are they all working on your end?

**Comment by ibobechko** [comment]
Yeah I didn’t finish last step in @newEvent scenario. It’s not suppose to
go through for now. I will work on it tomorrow. Thank you for checking!

**Comment by ValeriySyutkin** [comment]
All is good. Now i kinda regret that we did not create a Develop branch, like and extra protection layer so we can all work in a personal branches, merge/update to develop branch and only everything that working already merge to master. Good job anyways

**Comment by ibobechko** [comment]
I agree

**Comment by ValeriySyutkin** [comment]
i just checked again your code since just for practice purpuse im doing same task. (in my regular study project from Gurhan)
so your last step of first 3 scenarious you shuold do assertion. You are using browser ultil method wait which is not verifying anything. You want asserttrue. url contains day, week, month,. Also i would parametarise steps where they have  "day" "week" "month".  as well as last step  "day" "week" "month" so you can assert url contains those words Just want to point that oout so you can fix it

**Comment by ibobechko** [comment]
Thank you I will check tonight. I really don’t know why I didn’t use
assert, which is super important step lol I wanted to go back to my code
anyway to double check everything, thank you I appreciate your input. I
feel like this is the way how we learn :)
And regarding parameterization I was thinking to use it but then I figured
that we can hard code it only because there is no scenerio why we would
change the scenerio I mean if we checking day it would be day anyway
Just shooting you my thoughts

**Comment by ValeriySyutkin** [comment]
it is good idea to use parametirisation so you can reuse same line for the same scenario
literally first 3 scenarios are the same, so you dont need to create new line. Here is my version :
Scenario: User can display daily calendar view
    Given user is already logged in to trycloud.net and is on dashboard page
    When user clicks calendar button
    And usel clicks tree line button
    And user clicks "Day" button
    Then user can see "Day"ly calendar view
(in a last step you just assert url contains that parametisised word)
literally 3 AC can use same code lines , and last line will look like this 
Then user can see "Week"ly calendar view,
Then user can see "Month"ly calendar view... so in assertion you cn just use that parameterized word

**Comment by ibobechko** [comment]
yes I wanted to do it like this but than I thought about Jira and how
properly write scenarios so „business people” will understand what we did
Idk
I get what you are saying and I did like this before but than I changed it
to 3 scenarios lol

**Comment by ValeriySyutkin** [comment]
well i think my variant is kinda readable in jira for busyness people too, since it is: Then user can see "Day"ly calendar view ...and not: Then verify url contais "day"  Assert.AssertTrue(urlContains.("day")) lol

**Comment by ValeriySyutkin** [comment]
when i finish your task as a practice ill show you my complete variant

**Comment by ibobechko** [comment]
Sounds good

**Pull request merged**
